/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "ID6yybTqsxfwEyOgos0i33w",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        vpcConfig: {
            vpcId: "vpc-0d7f5bba2af2db4ed",
            securityGroupIds: [
                "sg-05d6ea8a12ce1d304"
            ],
            subnetAvailabilityZones: [
                {
                    subnetId: "subnet-01069a728300facc8",
                    availabilityZone: "eu-central-1a"
                },
                {
                    subnetId: "subnet-00c0632b896e85fdb",
                    availabilityZone: "eu-central-1b"
                }
            ]
        }
    }
}).schema({
    "bookings": a.model({
        during: a.string(),
        id: a.integer().required()
    }).identifier([
        "id"
    ])
});
