CREATE TABLE
  "public"."services" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "name" TEXT NOT NULL,
    "duration" INTERVAL DAY TO MINUTE NOT NULL,
    CONSTRAINT services_pkey PRIMARY KEY (id)
  );

ALTER TABLE "public"."services" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert for authenticated users only" ON "public"."services" AS PERMISSIVE FOR INSERT TO authenticated
WITH
  CHECK (TRUE);

CREATE POLICY "Enable read access for all users" ON "public"."services" AS PERMISSIVE FOR
SELECT
  TO public USING (TRUE);
