BEGIN;

CREATE TABLE
  public.opening_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    monday_from TIME WITHOUT TIME ZONE NULL,
    monday_to TIME WITHOUT TIME ZONE NULL,
    tuesday_from TIME WITHOUT TIME ZONE NULL,
    tuesday_to TIME WITHOUT TIME ZONE NULL,
    wednesday_from TIME WITHOUT TIME ZONE NULL,
    wednesday_to TIME WITHOUT TIME ZONE NULL,
    thursday_from TIME WITHOUT TIME ZONE NULL,
    thursday_to TIME WITHOUT TIME ZONE NULL,
    friday_from TIME WITHOUT TIME ZONE NULL,
    friday_to TIME WITHOUT TIME ZONE NULL,
    saturday_from TIME WITHOUT TIME ZONE NULL,
    saturday_to TIME WITHOUT TIME ZONE NULL,
    sunday_from TIME WITHOUT TIME ZONE NULL,
    sunday_to TIME WITHOUT TIME ZONE NULL,
    CONSTRAINT opening_hours_pkey PRIMARY KEY (id)
  ) TABLESPACE pg_default;

ALTER TABLE "public"."opening_hours" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "public"."opening_hours" AS PERMISSIVE FOR
SELECT
  TO public USING (TRUE);

COMMIT;
